---
title: "Urban Redcedar Analyses - Welcome"
author: "Joey Hulbert"
date: "2023-04-16"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: true
    toc_depth: 3
---


|            |            |            |            |
|:----------:|:----------:|:----------:|:----------:|
|[Welcome](https://jmhulbert.github.io/redhot)|[Data](https://jmhulbert.github.io/redhot/data)|[Analyses](https://jmhulbert.github.io/redhot/analyses)|[Discussion](https://jmhulbert.github.io/redcedar/discussion)|
|             |           |            |            |


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Intro

The RedHot analyses were completed to study relationships between the health of western redcedar and urban environmental factors.

* We were interested in the factors that affect urban tree health such as:
    + Urban Heat
    + Impermeable Surface
    + Pollution
    + Climate Variables
    + Wealth
    + Tree Size
    + Tree Species

# Data

* Analyses were completed with the following Data
  + Redcedar health data were collected by community scientists in the [Western Redcedar Dieback Map](https://www.inaturalist.org/projects/western-redcedar-dieback-map) project on iNaturalist. 
  + Urban heat data were commissioned by three cities in the northwest using methods described in [Voelkel and Shandas (2017)](https://www.mdpi.com/2225-1154/5/2/41). 
  + Home Owners Loan Corporation Maps were downloaded from the Mapping Inequality Project at the following links
    + [Tacoma](https://dsl.richmond.edu/panorama/redlining/WA-Tacoma)
    + [Portland](https://dsl.richmond.edu/panorama/redlining/OR-Portland)
    + [Seattle](https://dsl.richmond.edu/panorama/redlining/WA-Seattle)
  + Environmental Health Disparity Data were downloaded from the [Washington Tracking Network](https://geo.wa.govsets/WADOH::full-environmental-health-disparities-version-2-extract/explore)

Data for the below metrics are included in the [data](https://jmhulbert.github.io/data/), but not all have been investigated in the [analyses](https://jmhulbert.github.io/analyses/) yet. 

* Available data presently
    + Diesel exhaust
    + Ozone
    + Urban Heat
    + Wealth - poverty
    + Tree size
    + Proximity to heavy traffic roadways

# Approaches

The relationship between redcedar and urban metrics were investigated with generalized mixed effect models. [More information about the analyses is available](https://jmhulbert.github.io/analyses/)


# Extra Questions

* Possible additional questions to explore
  + Which pollution data are important for determining tree health?
  + Are Temperatures higher for trees in urban areas of King County?
  + Are income and tree size important effects for the vulnerability of redcedar to urban heat? 



