---
title: "Discussion"
author: "Joey Hulbert"
date: "Last Update: `r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: true
    toc_depth: 3
---


|            |            |            |            |            |
|:----------:|:----------:|:----------:|:----------:|:----------:|
|[Welcome](https://jmhulbert.github.io/redhot)|[Data](https://jmhulbert.github.io/redhot/data)|[Analyses](https://jmhulbert.github.io/redhot/analyses)|[Discussion](https://jmhulbert.github.io/redhot/discussion)|[Maps](https://jmhulbert.github.io/redhot/maps)
|             |           |            |            |            |

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Purpose

The purpose of this page is to share discussion points or feedback for approaches and interpretations. 


# Approaches

The relationship between redcedar and urban heat were investigated with generalized mixed effect models with these [data](https://jmhulbert.github.io/data/) and [analyses](https://jmhulbert.github.io/analyses/).


# Findings

Overall, the probability of a tree having top dieback or being classified as unhealthy increased with increases in temperatures above average, but there was no evidence the probability of a tree being classified as thinning is related to afternoon heat. 

Evidence for increases in the probability of having top dieback with increases in afternoon temperatures was found in Portland and King County datasets, but not Tacoma.

* General results
  + probability a tree was classified as unhealthy increased with urban heat
  + After noon temperature best fit
    + More investigation into the importance of morning, afternoon, or evening temperature would be valuable. 
  + No evidence for effect of co-factors
  + Rural temps were higher than urban temps in king county

# Questions of interest

* Initial Questions of Interest
  + Does urban heat increase the probability of trees being classified as unhealthy?
    + which temperature time is most important (e.g. morning, afternoon, evening, daily avg?)
  + Does urban heat increase the probability of trees being classified as dead?
  + Are increases in urban heat associated with increases in percent canopy dieback?
  + Are percent poverty, HOLC rating, or environmental health disparity ranks associated with increases in probability of trees being classified as unhealthy? 
  + Do urban trees have higher proportions of unhealthy trees than rural trees?
  + Does tree size affect the tree's vulnerability to urban heat?

# Possible co-factors

It may be possible to include more detail in recommendations if we explore the relationship between tree health and urban heat while accounting for co-factors. 

Most of these co-factors are categorical so including 2 co-factors with 4 levels would include 16 different combinations.. we likely do not enough data for that. 

+ Possible co-factors to consider
  + Tree Size (small, medium, large)
  + Site Type (urban, suburban, rural)
  + Location Description (In a forest, in a field, along a road)
  + Water availability, water in summer? 

# Approach Considerations

* Aspects to consider
  + Should we remove observations with very poor positional accuracy? 
  + More investigation into the timing of heat?
    + e.g. which temperatures (morning, afternoon, eve) are most important for determining tree health?
    + Check how dist from avg is calculated based on daily average temperature
  + Including dead trees?
    + Current analysis does not include dead trees because
      + there are a number of other factors that may have led to the dead of those trees
      + could not account for 1 inflation with glmmTMB package
    + Beta logistic regression analysis does not include dead trees because there are a number of other factors that may have led to the dead of those trees
      + Removing dead trees also removes the issue where we could not account for 1 inflation with glmmTMB package
      + Are there other random effects we should account for (e.g site type or user?)
  + Removing Hoyt Arboretum Trees? 
    + Caclulating Distance from mean after removing Hoyt
  + should we remove observations with very poor positional accuracy?  

* Binomial Distribution Analyses
  + [Urban Heat Analysis](https://jmhulbert.github.io/redhot/analyses/heat/binomial/)
  + [1930s Home Owner Loan Corporation Ranks Analysis](https://jmhulbert.github.io/redhot/analyses/holc/binomial/)
  + [Environmental Health Disparity Data Analysis](https://jmhulbert.github.io/redhot/analyses/ehd/binomial/)
  + [Portland Urban Heat Analysis](https://jmhulbert.github.io/redhot/analyses/portland/heat/binomial/)
  
  
Eish, the portland dataset as is, only includes 15 trees with dead tops. 
  
Should we remove other tree health categories (e.g. other or thinning) in analyses? for example, should we only include 'dead top' and 'healthy' trees when doing a dead top analysis?

Yes! Because some of the trees in the 'other category' may have had multiple symptoms (thinning and dead top) so saying it is tree that is not thinning or does not have a dead top may be false. 

Removing the other categories (thinning or dead top) when comparing these categorizes also makes sense because be just want to compare thinning to healthy trees not thinning to dead top. 

Filtering trees to dead tops or healthy did not improve the significance of the tacoma dead top model. 

Why was there no evidence of a relationship in Tacoma?

* How to handle outliers?
  + Accounted for currently
      + removed outliers of trees with < -8 dist.from.mean.af
  + Not accounted for currently   
    + check outliers for toxic release, whats up with those?
    + check outliers with healthy trees with 100% dieback or with any % dieback values

* Interactions?
  + Heat and Pollution 
    + Does dieback increase with increases in heat *pollution?*
  + Heat and Poverty
    + Are the impacts of urban heat on dieback worse for those in poverty?

[Analyses of Portland data only](https://jmhulbert.github.io/redhot/analyses/portland/heat/binomial/) indicate there is a relationship between tree health and afternoon heat (DN_AF1) - non standardized. 
The probability of a tree having top dieback increased with afternoon heat. However, no evidence was found for a relationship between crown thinning and afternoon heat. *Perhaps there is a relationship with morning or evening temperatures?* However, it could also be that the observers are not as confident in recognizing trees as thinning. 


Effects of co-variates without urban heat
chi squared - proporitons are different than they would be with chance

## Data limitations

Preliminary analyses of data limited to those with [HOLC grades](https://jmhulbert.github.io/redhot/analyses/holc/binomial/) (n=395) may not have enough observations. For example, even when distance from mean afternoon temp was included as a co-factor, there was no evidence of a realtionship with heat. 

Similarly, about 500 observations (oregon's) were dropped for analyses limited to observations with EHD data (n=787). Testing hypotheses with EHD data may be best accomplished by including the full dataset, rather than those shared only from King County or Tacoma. 

Removal of Hoyt Trees
Removal of Dead Trees

## Data QA QC

Eight other tree species were added to the project, but the iNaturalist community helped id the trees correctly. 

How many identifiers were there? How many observers were there? 

# Extra Questions

* Possible additional questions to explore
  + Which pollution data are affect the probability of tree health classification?
  + Are Temperatures higher for trees in urban areas of King County?
  + Are income and tree size important co-factors to the relationship between redcedar health and urban heat? 

* Additional Factors to consider as impacts to urban tree health. 
    + Impermeable Surface (could be calculated for buffers around Tacoma trees at least)
    + Pollution
    + Climate Variables
    + Wealth
    + Tree Size

Additional possible co-factors in urban heat analyses 
  + equity 
    + not sure if there is a good metric in the data for this, but maybe income would be related to expenses for tree care
    + however, it may be correlated with urban heat






## Jim's study

143 trees in tacoma were revisited during the fall season in 2023. These trees were previously added to the WRDM. Trees were tagged in a second project,  Data for 2023 fall percent canopy dieback, seasonal branch browning percent, and relative cone crop were added. 

* Questions
  + change in dieback in relation to access to summer water
  + relative cone crop in relation to access to summer water
  + persent seasonal browning in relation to access to summer water

## Dieback and Pollution

* Questions
  + Which pollution data are important for determining tree health?
  + Does dieback increase with increases in pollution?
    
# Additional Data

+ Home Owners Loan Corporation Maps were downloaded from the Mapping Inequality Project at the following links:
    + [Tacoma](https://dsl.richmond.edu/panorama/redlining/WA-Tacoma)
    + [Portland](https://dsl.richmond.edu/panorama/redlining/OR-Portland)
    + [Seattle](https://dsl.richmond.edu/panorama/redlining/WA-Seattle)
  + Environmental Health Disparity Data were downloaded from the [Washington Tracking Network](https://fortress.wa.gov/doh/wtnibl/WTNIBL/).


Data for the below metrics were included in the [data]((https://jmhulbert.github.io/redhot/data)), but not all were investigated in the [analyses](https://jmhulbert.github.io/redhot/analyses/) yet. 

* Available data 
    + iNaturalist Data
      + Tree health conditions
      + Percent Dieback
      + Number of additional unhealthy trees
      + Tree size
      + Site type (urban, suburban, rural)
      + Location description (roadside, park or yard, forest edge, inside forest)
      + Summer access to water
    + Urban heat
    + HOLC Grade
    + EHD Data (see [V2.0 Report](https://doh.wa.gov/sites/default/files/2022-07/311-011-EHD-Map-Tech-Report_0.pdf?uid=62e46bbc98fad) for more details)
      + Indicators in Pollution Burden
        + Environmental Exposures
          + Diesel exhaust
          + Ozone
          + PM2.5
          + Toxic Release
          + Proximity to heavy traffic roadways
        + Environmental Effects
          + Lead risk from housing
          + Proximity to hazardous waste treatment storage
          + Proximity to superfund sites
          + wastewater discharge
      + Indicators of Population Characteristics
        + Sensitive Populations
          + Death from cardiovascular disease
          + Low birth weight
        + Socioeconomic Factors
          + No high school diploma
          + Unaffordable housing
          + Transportation expense
          + Limited English
          + People living in poverty
          + Race (people of color)
          + Unemployment






# References

 + Voelkel, J., and Shandas, V. (2017). Towards Systematic Prediction of Urban Heat Islands: Grounding Measurements, Assessing Modeling Techniques. Climate 5, 41. doi: 10.3390/cli5020041.
