---
title: "Tree Health and Urban Heat Analyses"
author: "Joey Hulbert"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

|            |            |            |            |            |
|:----------:|:----------:|:----------:|:----------:|:----------:|
|[Welcome](https://jmhulbert.github.io/redhot)|[Data](https://jmhulbert.github.io/redhot/data)|[Analyses](https://jmhulbert.github.io/redhot/analyses)|[Discussion](https://jmhulbert.github.io/redhot/discussion)|[Maps](https://jmhulbert.github.io/redhot/maps)
|             |           |            |            |            |



# Purpose

Relationships between the health of redcedar and urban heat were explored with generalized linear mixed effect models. 


# Models

+ List of Models
  + [All Areas Analyses](https://jmhulbert.github.io/redhot/analyses/heat/all-areas)
    + Model Selection - Temperature Time Series Comparison
      +  binomial.daily <- glmmTMB(binary.tree.canopy.symptoms ~ dist.from.mean.daily + (1|Area),family=binomial,data=data)
      + binomial.am <- glmmTMB(binary.tree.canopy.symptoms ~ dist.from.mean.am + (1|Area),data=data,family=binomial)
      + binomial.af <- glmmTMB(binary.tree.canopy.symptoms ~ dist.from.mean.af + (1|Area),data=data,family=binomial)
      + binomial.pm <- glmmTMB(binary.tree.canopy.symptoms ~ dist.from.mean.pm + (1|Area),data=data,family=binomial)
    + Core Response Variables
      + **Response 1.0** - Binary Health Response (healthy, unhealthy)
        + binomial.af <- glmmTMB(binary.tree.canopy.symptoms ~ dist.from.mean.af + (1|Area),data=data,family=binomial)
      + **Response 2.0** - Binary Top-Dieback (healthy, dead top)
        + top.dieback.binomial.af <- glmmTMB(top.dieback ~ dist.from.mean.af + (1|Area),data=data,family=binomial)
      + **Response 3.0** - Binary Thinning Response (healthy, thinning)
        + thinning.binomial.af <- glmmTMB(thinning ~ dist.from.mean.af + (1|Area),data=data,family=binomial)
    + Co-Factors
      + Co-Factor Model 1 - including addition of location
        + **Response 1.1** - Binary Health Response (healthy, unhealthy)
          - binomial.af.size <- glmmTMB(binary.tree.canopy.symptoms ~ dist.from.mean.af +  tree.size.simplified +(1|Area),data=data.size.site.filter,family=binomial)
        + **Response 2.1** - Binary Top-Dieback (healthy, dead top)
        + **Response 3.1** - Binary Thinning Response (healthy, thinning)
      + Co-Factor Model 2 - including addition of tree size
        + **Response 1.2** - Binary Health Response (healthy, unhealthy)
          + binomial.af.site <- glmmTMB(binary.tree.canopy.symptoms ~ dist.from.mean.af +  tree.size.simplified +(1|Area),data=data.size.site.filter,family=binomial)
        + **Response 2.2** - Binary Top-Dieback (healthy, dead top)
        + **Response 3.2** - Binary Thinning Response (healthy, thinning)
  + [Portland Analyses](https://jmhulbert.github.io/redhot/analyses/heat/portland)
    + Model Selection - Temperature Time Series Comparison
      + binomial.daily <- glmmTMB(binary.tree.canopy.symptoms ~ mean.temp.daily ,family=binomial,data=data)
      + binomial.am <- glmmTMB(binary.tree.canopy.symptoms ~ DN_AM1 ,data=data,family=binomial)
      + binomial.af <- glmmTMB(binary.tree.canopy.symptoms ~ DN_AF1 ,data=data,family=binomial)
      + binomial.pm <- glmmTMB(binary.tree.canopy.symptoms ~ DN_PM1,data=data,family=binomial)
    + **Response 1.3** - Binary Health Response (healthy, unhealthy)
      + binomial.af <- glmmTMB(binary.tree.canopy.symptoms ~ DN_AF1 ,data=data,family=binomial)
    + **Response 2.3** - Binary Top Dieback (healthy, dead top)
      + top.dieback.binomial.af <- glmmTMB(top.dieback ~ DN_AF1,data=data,family=binomial)
    + **Response 3.3** - Binary Thinning Response (healthy, thinning)
      + thinning.binomial.af <- glmmTMB(thinning ~ DN_AF1,data=data,family=binomial)
  + [Tacoma Analyses](https://jmhulbert.github.io/redhot/analyses/heat/tacoma)
    + Model Selection - Temperature Time Series Comparison
      + binomial.daily <- glmmTMB(binary.tree.canopy.symptoms ~ mean.temp.daily ,family=binomial,data=data)
      + binomial.am <- glmmTMB(binary.tree.canopy.symptoms ~ DN_AM1 ,data=data,family=binomial)
      + binomial.af <- glmmTMB(binary.tree.canopy.symptoms ~ DN_AF1 ,data=data,family=binomial)
      + binomial.pm <- glmmTMB(binary.tree.canopy.symptoms ~ DN_PM1,data=data,family=binomial)
    + **Response 1.4** - Binary Health Response (healthy, unhealthy)
      + binomial.af <- glmmTMB(binary.tree.canopy.symptoms ~ DN_AF1 ,data=data,family=binomial)
    + **Response 2.4** - Binary Top Dieback (healthy, dead top)
      + top.dieback.binomial.af <- glmmTMB(top.dieback ~ DN_AF1,data=data,family=binomial)
    + **Response 3.4** - Binary Thinning Response (healthy, thinning)
      + thinning.binomial.af <- glmmTMB(thinning ~ DN_AF1,data=data,family=binomial)
  + [King County Analyses](https://jmhulbert.github.io/redhot/analyses/heat/king-county)
    + Model Selection - Temperature Time Series Comparison
      + binomial.daily <- glmmTMB(binary.tree.canopy.symptoms ~ mean.temp.daily ,family=binomial,data=data)
      + binomial.am <- glmmTMB(binary.tree.canopy.symptoms ~ DN_AM1 ,data=data,family=binomial)
      + binomial.af <- glmmTMB(binary.tree.canopy.symptoms ~ DN_AF1 ,data=data,family=binomial)
      + binomial.pm <- glmmTMB(binary.tree.canopy.symptoms ~ DN_PM1,data=data,family=binomial)
    + **Response 1.5** - Binary Health Response (healthy, unhealthy)
      + binomial.af <- glmmTMB(binary.tree.canopy.symptoms ~ DN_AF1 ,data=data,family=binomial)
    + **Response 2.5** - Binary Top Dieback (healthy, dead top)
      + top.dieback.binomial.af <- glmmTMB(top.dieback ~ DN_AF1,data=data,family=binomial)
    + **Response 3.5** - Binary Thinning Response (healthy, thinning)
      + thinning.binomial.af <- glmmTMB(thinning ~ DN_AF1,data=data,family=binomial)
    
# Model Approaches Considered

* Approaches considered
  + ordinal vs ordinal - chi squared 
    + e.g. health category vs holc grade
  + categorized as 0 or 1 - binomial categorical
    + e.g. probability of healthy vs unhealthy - does that increase with afternoon temperature
  + categorized as healthy, unhealthy, dead - ordinal distribution
  + Increases in percent (proportion) canopy dieback - beta distribution 
    + likley need to account for zero inflation
      + e.g. does increases in urban heat increase likelyhood of having dieback (zi model) AND does increases in urban heat increase precent dieback proportion for trees with some dieback (conditional model).

## Binomial Distribution

+ Response variables: 
  + *healthy, unhealthy*
  + *healthy, dead top*
  + *healthy, thinning*
  
Excluding dead trees might make sense biologically, because we're not sure what factor actually killed the tree. Also the dead trees may have been dead for different lengths of time. Some may have been affected by heat, where others had not. There is good biological reasoning to exclude the dead trees. 

## Ordinal Distribution

[Ordinal Distribution Analysis](https://jmhulbert.github.io/redhot/analyses/heat/ordinal/)

Response variable: category: *healthy, unhealthy, dead*

If we want to include three categories in our response variable (healthy, unhealthy, dead), we may want to consider an ordinal distribution. An ordinal distribution would be most appropriate for these categories compared to a multinomial distribution because the categories have a natural order. 

Alternate response variable

Response variable: category: *0% Dieback, 1-29% Dieback, 30-59% dieback, 60-99% dieback, dead*


## Beta Distribution

[Beta Distribution Analysis](https://jmhulbert.github.io/redhot/analyses/heat/beta/)

Response variable: *percent canopy dieback*

Because the response variable is percent (we can consider it as proportion too) we can do regression using a beta distribution (comparing shapes) rather than a linear regression. We also need to use an distribution zero or one inflated rate. 

Note, beta distribution analyses only included observations where community scientists estimated the percent canopy dieback (which was optional). 

We considered converting the categorical variable for percent canopy affected (e.g. 1-30% is affected, 31-60% is affected, etc), but determined it was too awkward and innacurate. 


### Zero inflated beta regression

* We referenced the following documents for guidance:
+ Websites
  + [GLMM FAQ](https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html)
+ Blog Posts
  + [Andrew Heiss's blog post](https://www.andrewheiss.com/blog/2021/11/08/beta-regression-guide/#linear-probability-models) 
+ Vignettes
  + ['Get Started'](https://glmmtmb.github.io/glmmTMB/articles/glmmTMB.html) guide from glmmTMB
+ Github/Stack Exchange Issue Posts
  + [Ben Bolker discussion about zero inflated betas and zero-one inflated betas](https://github.com/glmmTMB/glmmTMB/issues/507)
+ Youtube Videos
  + [Statistical Methods Series: Zero-Inflated GLM and GLMM](https://www.youtube.com/watch?v=ISN9SE__QOU&t=35s)
    + [Supplementary example code useful for glmmTMB](https://github.com/eco4cast/Statistical-Methods-Seminar-Series/blob/main/zuur-ieno_zero-inflated-models/RCode/Owls_ESA.R)
+ Background Papers
  + [Generalized linear mixed models: a practical guide for ecology and evolution](https://www.sciencedirect.com/science/article/abs/pii/S0169534709000196) 
  + [Chapter 13 Linear and generalized linear mixed models](https://academic.oup.com/book/41052/chapter-abstract/349379451?redirectedFrom=fulltext&login=false).
  + [glmmTMB Balances Speed and Flexibility
Among Packages for Zero-inflated
Generalized Linear Mixed Modeling](https://journal.r-project.org/archive/2017/RJ-2017-066/RJ-2017-066.pdf)


#### Interpreting zi Model Outputs

The conditional output is indicating that for all observations with greater than 0 dieback proportions, distance from mean am influences the proprtion of dieback. The zi model tells us which predictor increases the propability of non-zero. 
> interesting that the distance from mean am has a negative estimate though - hard to know if it is observations higher than the mean or lower than the mean (ie as temp increases, distance from mean decreases (but higher or lower than mean))

Including a predictor in the zi= bit of the model would test whether heat influences whether there is dieback at all. 

Possible understanding from: https://stats.stackexchange.com/questions/466047/interpreting-output-for-glmmtmb-for-zero-inflated-count-data 


# References

  + Brooks, M. E., Kristensen, K., van Benthem, K. J., Magnusson, A., Berg, C. W., Nielsen, A., Skaug, H. J., Machler, M., & Bolker, B. M. (2017). glmmTMB balances speed and flexibility among packages for Zero-inflated Generalized Linear Mixed Modeling. The R Journal, 9(2), 378-400. https://doi.org/10.32614/RJ-2017-066  
    + Answers reference 'pages 382-383 explain all components of the model summary'
 + Voelkel, J., and Shandas, V. (2017). Towards Systematic Prediction of Urban Heat Islands: Grounding Measurements, Assessing Modeling Techniques. Climate 5, 41. doi: 10.3390/cli5020041.

