---
title: "iNaturalist Data Summaries"
author: "Joey Hulbert"
date: "Last Update: `r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: true
    toc_depth: 3
---


|            |            |            |            |            |
|:----------:|:----------:|:----------:|:----------:|:----------:|
|[Welcome](https://jmhulbert.github.io/redhot)|[Data](https://jmhulbert.github.io/redhot/data)|[Analyses](https://jmhulbert.github.io/redhot/analyses)|[Discussion](https://jmhulbert.github.io/redhot/discussion)|[Maps](https://jmhulbert.github.io/redhot/maps)
|             |           |            |            |            |


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(gghalves)
library(patchwork)
library(scales)
```



# Purpose

The purpose of this page is to provide summaries of the data from the WRDM observations included in these [analyses](https://jmhulbert.github.io/redhot/analyses).

# Data

iNaturalist data were downloaded from the [Western Redcedar Dieback Map](https://www.inaturalist.org/projects/western-redcedar-dieback-map) on 1.13.24.

```{r}
data <- read.csv('https://raw.githubusercontent.com/jmhulbert/redhot/main/data/urban-data-modified.csv')
```

# Data Summaries

## Community scientists

```{r}
data %>% group_by(user_login) %>% count()
```

```{r}
data %>% summarize(n.participants=n_distinct(user_id),n.obs=n())
```

```{r}
data %>% group_by(Area) %>% summarize(n.participants=n_distinct(user_id),n.obs=n())
```
## Tree Health

```{r}
data %>% group_by(reclassified.tree.canopy.symptoms) %>% summarize(n.obs=n())
```

```{r}
data %>% group_by(reclassified.tree.canopy.symptoms) %>% summarize(n.obs=n())
```



