---
title: "Ordinal Distribution Response to Urban Heat"
author: "Joey Hulbert"
date: "`r Sys.Date()`"
output: html_document
---

|            |            |            |            |
|:----------:|:----------:|:----------:|:----------:|
|[Welcome](https://jmhulbert.github.io/redhot)|[Data](https://jmhulbert.github.io/redhot/data)|[Analyses](https://jmhulbert.github.io/redhot/analyses)|[Discussion](https://jmhulbert.github.io/redcedar/discussion)|
|             |           |            |            |


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(corrplot)
library(knitr)
library(kableExtra)
library(gghalves)
library(patchwork)
library(scales)
library(glmmTMB)
library(bbmle)
library(DHARMa)
```


# Purpose

The purpose of this page is to summarize an investigation of **tree health categories** as a *categorical* response to urban heat (temperatures).

Response variable: category: *healthy, unhealthy, dead*


# Read Data

```{r}
data <- read.csv('https://raw.githubusercontent.com/jmhulbert/redhot/main/data/urban-data-modified.csv')
```



